### ISSUE TITLE
lib/chat-message-streaming-examples-stack.ts:259:27 - error TS1109: Expression expected.

### ISSUE THREAD

**Issue by jww** [amazon-connect/amazon-connect-message-streaming-examples#10]
There seems to be an inadvertent change to the lib/chat-message-streaming-examples-stack.ts file.

https://github.com/amazon-connect/amazon-connect-message-streaming-examples/blob/bff213c3ede5e5c27dda31091cf0262ccc88441c/lib/chat-message-streaming-examples-stack.ts#L259

node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
lib/chat-message-streaming-examples-stack.ts:259:27 - error TS1109: Expression expected.

259           `arn:aws:s3:::${}/*`,

**Comment by ahmedyounis** [comment]
Getting the same error.    Can we get an update on when this can be resolved? 


⨯ Unable to compile TypeScript:
lib/chat-message-streaming-examples-stack.ts:259:27 - error TS1109: Expression expected.

259           `arn:aws:s3:::${}/*`,
                              ~

Subprocess exited with error 1

**Comment by ahmedyounis** [comment]
Fixed the issue by reverting line 259 to what it was in the initial commit:

changed this:
`arn:aws:s3:::${}/*`,

to this
          `arn:aws:mobiletargeting:${this.region}:${this.account}:apps/${this.node.tryGetContext("pinpointAppId")}/messages`,

cdk deploys fine after that change

**Comment by kqia040** [comment]
Thanks for calling this out, addressed this (rolled back to previous version).
