### ISSUE TITLE
ChatMessageStreamingExamplesStack constructor error message points to missing Amazon Connect ARN instead of contactFlowId

### ISSUE THREAD

**Issue by muratilkdogan** [amazon-connect/amazon-connect-message-streaming-examples#4]
ChatMessageStreamingExamplesStack constructor error message points to missing Amazon Connect ARN instead of  contactFlowId. 

https://github.com/amazon-connect/amazon-connect-message-streaming-examples/blob/d654cef75dfc0dc3b37b4a1726c2e27e3453066b/lib/chat-message-streaming-examples-stack.ts#L38

**Comment by kqia040** [comment]
Thanks! updated the error msg
