### ISSUE TITLE
The signature is not detected correctly because the type is incorrect.

### ISSUE THREAD

**Issue by intptr-t** [amazon-connect/amazon-connect-message-streaming-examples#5]
The return value of `fb.validateRequest(...)` is a Promise<boolean>, so await is required.
If there is no "await", the signature detection will always succeed. (`if (!validRequest)` will be determined to be false)

**caller**
https://github.com/amazon-connect/amazon-connect-message-streaming-examples/blob/f5f8712e581ccc44ee5c6d40ea5df2874cb506c0/src/lambda/inboundMessageHandler/index.js#L30

**callee**
https://github.com/amazon-connect/amazon-connect-message-streaming-examples/blob/f5f8712e581ccc44ee5c6d40ea5df2874cb506c0/src/lambda/inboundMessageHandler/lib/handlers/facebook.js#L143

**Comment by kqia040** [comment]
Closing issue as the PR is merged
