### ISSUE TITLE
message for the facebook part is not getting transfered to aws connect instance

### ISSUE THREAD

**Issue by karantesting** [amazon-connect/amazon-connect-message-streaming-examples#8]
https://aws.amazon.com/blogs/contact-center/adding-digital-messaging-channels-to-your-amazon-connect-contact-center/

According to the blog, the fb real time chat api is not working at my end.
<img width="1104" alt="Screenshot 2021-11-22 at 1 19 43 PM" src="https://user-images.githubusercontent.com/93683003/142822991-72c35cae-b576-4c09-8653-ba079a5744a9.png">

**Comment by kqia040** [comment]
A few questions. 

- Is the webhook configured to send "messages"?
- Is the inboundLambda function receiving these events? You can check the Lambda logs for that, for more detailed debugging logs, in the Lambda environment variable please update Debug to be true.
- If you are sending messages from a personal FB account (who is not a developer on the app) you will need to validate the FB app with FB.

In general, the troubleshooting path is to figure out if FB is sending the messages at all (check API Gateway/Inbound Lambda/Amazon Connect Contact Flow logs in Cloudwatch) if AWS is receiving the messages, then troubleshoot downstream to figure out why the messages are not reaching Amazon Connect.

If AWS is not receiving the messages, then the question is why FB isn't sending the messages

**Comment by kqia040** [comment]
Any updates here? Resolving for for now, feel free to re-open

**Comment by karantesting** [comment]
Hi,

Can you let me know the process to validate the FB account.

Regards
Karan
